// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjrIE5EJi3CRf0O7gujAIh61_7p5_Puo',
    appId: '1:669544143843:web:9e21ab2ef902868c8f9ed6',
    messagingSenderId: '669544143843',
    projectId: 'brainsync6325',
    authDomain: 'brainsync6325.firebaseapp.com',
    storageBucket: 'brainsync6325.appspot.com',
    measurementId: 'G-WKVBY4Z63Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3hUG8AWkjXxlknxy3RRAej7xqkASsHsQ',
    appId: '1:669544143843:android:25cf25b7485f08f38f9ed6',
    messagingSenderId: '669544143843',
    projectId: 'brainsync6325',
    storageBucket: 'brainsync6325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz08VIOv_b8NvfRGbSniTXKv0rd_7pjDY',
    appId: '1:669544143843:ios:d52c66a15167989b8f9ed6',
    messagingSenderId: '669544143843',
    projectId: 'brainsync6325',
    storageBucket: 'brainsync6325.appspot.com',
    androidClientId: '669544143843-f060etkffkt2m8qnnmea2367qhlh6l0q.apps.googleusercontent.com',
    iosClientId: '669544143843-147do1r0grqlenusfnpjjp3s67nb3m3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz08VIOv_b8NvfRGbSniTXKv0rd_7pjDY',
    appId: '1:669544143843:ios:d52c66a15167989b8f9ed6',
    messagingSenderId: '669544143843',
    projectId: 'brainsync6325',
    storageBucket: 'brainsync6325.appspot.com',
    androidClientId: '669544143843-f060etkffkt2m8qnnmea2367qhlh6l0q.apps.googleusercontent.com',
    iosClientId: '669544143843-147do1r0grqlenusfnpjjp3s67nb3m3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJjrIE5EJi3CRf0O7gujAIh61_7p5_Puo',
    appId: '1:669544143843:web:3dc7b154cf842cf38f9ed6',
    messagingSenderId: '669544143843',
    projectId: 'brainsync6325',
    authDomain: 'brainsync6325.firebaseapp.com',
    storageBucket: 'brainsync6325.appspot.com',
    measurementId: 'G-MW6K1945E2',
  );

}